### ISSUE TITLE
Missing dependency for @types/launchdarkly-eventsource

### ISSUE THREAD

**Issue by tlevesque-ueat** [Unleash/unleash-client-node#705]
### Describe the bug

Got this error after upgrading from 6.1.3 to 6.4.3:

> tsc -b tsconfig.build.json
> Error: node_modules/unleash-client/lib/repository/index.d.ts(9,29): error TS7016: Could not find a declaration file for module 'launchdarkly-eventsource'. '/home/runner/work/(redacted)/node_modules/launchdarkly-eventsource/lib/eventsource.js' implicitly has an 'any' type.
> Try `npm i --save-dev @types/launchdarkly-eventsource` if it exists or add a new declaration (.d.ts) file containing `declare module 'launchdarkly-eventsource';`

Shouldn't `@types/launchdarkly-eventsource` be listed as a dependency?

### Steps to reproduce the bug

In a project using Typescript, upgrade from 6.1.3 to 6.4.3 (not sure when the dependency on launchdarkly-eventsource was introduced, maybe 6.3.0)
Try to compile.

### Expected behavior

Should compile without issue

### Logs, error output, etc.

```bash
Error: node_modules/unleash-client/lib/repository/index.d.ts(9,29): error TS7016: Could not find a declaration file for module 'launchdarkly-eventsource'. '/home/runner/work/(redacted)/node_modules/launchdarkly-eventsource/lib/eventsource.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/launchdarkly-eventsource` if it exists or add a new declaration (.d.ts) file containing `declare module 'launchdarkly-eventsource';`
```

### Unleash version

6.4.3

### Subscription type

Open source

### Hosting type

Hosted by Unleash

**Comment by tlevesque-ueat** [comment]
Oh wait. There isn't a `@types/launchdarkly-eventsource` package 🤦‍♂

**Comment by tlevesque-ueat** [comment]
Actually, I think something could still be done to improve the experience.
Right now I need to manually declare the module in a .d.ts file, like this:
```typescript
declare module 'launchdarkly-eventsource';
```
This could either be done directly in the `unleash-client` package, or the import from `launchdarkly-eventsource` could have a `//@ts-ignore` to ignore the missing typings.

**Comment by kwasniew** [comment]
Hi @tlevesque-ueat. The dependency was added for Unleash to test experimental SSE support. Can you let us know if you're getting this error when using unleash-client-node package as a dependency in your project or building a custom package from the sources yourself?

**Comment by Tymek** [comment]
@tlevesque-ueat did you try to add `node_modules` to `exclude` in your `tsconfig.json`?

**Comment by tlevesque-ueat** [comment]
> Hi @tlevesque-ueat. The dependency was added for Unleash to test experimental SSE support. Can you let us know if you're getting this error when using unleash-client-node package as a dependency in your project or building a custom package from the sources yourself?

Hi, I'm using it as a dependency in my project. I'm not using SSE support.

> @tlevesque-ueat did you try to add node_modules to exclude in your tsconfig.json?

It's already excluded.

**Comment by kwasniew** [comment]
Can you provide us with a minimal reproduction case so that we can debug it? Ideally a mini setup with package.json and tsconfig that you use?

**Comment by kwasniew** [comment]
BTW we already have // @ts-expect-error on the eventsource library usage itself.

**Comment by tlevesque-ueat** [comment]
OK, here's the simple repro I could make:
https://github.com/tlevesque-ueat/test-unleash-node-client

Build it with `npm run compile` to see the error.

Basically, I think you just need to import something from `unleash-client` with `noImplicitAny` set to true in the TS compilation options.

> BTW we already have // @ts-expect-error on the untyped eventsource library usage itself.

Yes, I noticed that. But it doesn't appear in the .d.ts file, which is read by the TS compiler...

**Comment by Tymek** [comment]
Ok, I found the root cause. I'll work on a solution. It's not about `noImplicitAny`, but about `skipLibCheck`.

**Comment by tlevesque-ueat** [comment]
@Tymek thanks!
Indeed, that works for me.
If you can figure out a way to make that unnecessary, even better! (your PR looks promising, but I'm not really a TS/JS expert...)

**Comment by tlevesque-ueat** [comment]
>  It's not about noImplicitAny, but about skipLibCheck.

Actually, I think it's both. The error will occur if `skipLibCheck` is false (which is the default) AND `noImplicitAny` is true.
Setting `noImplicitAny` to false also fixed the problem for me (but I don't want to, since it also applies to my own code).
Setting `skipLibCheck` to true is probably the best workaround, with no real downside, since I don't care about checking the types in my dependencies...

**Comment by Tymek** [comment]
Thanks a lot for reproducible example. It helped a lot, and will become a part of our tests.

**Comment by tlevesque-ueat** [comment]
Thanks for the fix!
Does that mean that with the latest version, I don't need the workarounds (`declare module` or `skipLibCheck`)?
